from domain.ports import IDetailPipeline
from domain.ports import IExtractionService
from domain.ports import ILinkExtractor
from domain.ports import ILinkSelectionStrategy
from domain.ports import IListPipeline
from domain.ports import IPageAnalyzer
from domain.ports import IPaginationService
from domain.ports import IPatternLearner
from domain.ports import IPlaywrightPaginationSession
